version: '3'
services:
   cassandra:
     hostname: cassandra
     image: "cassandra:latest"
     environment:
       - CASSANDRA_START_RPC=true
     ports:
       - "9042:9042"
   spark-master:
     hostname: spark-master
     image: 'spark'
     command: ["org.apache.spark.deploy.master.Master", "--ip", "spark-master", "--port", "7077", "--webui-port", "8080"]
     ports:
       - '7077:7077'
       - '8080:8080'
       - '4040:4040'
   spark-worker:
     image: 'spark'
     command: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--webui-port", "8081"]
     depends_on:
       - spark-master
     ports:
       - '8081:8081'
   spark:
     image: 'spark_connect'
     tty: true
